const BoughtCourses = [
    {
      image: "reactImage.jpeg",
      topic: "Complete JavaScript Guide",
      duration: "30 hours",
      lastUpdated: "Dec 2023",
      rating: 4.8,
      peopleBought: 3200,
      price: "₹649",
    },
    {
      image: "reactImage.jpeg",
      topic: "Mastering React.js",
      duration: "25 hours",
      lastUpdated: "Nov 2023",
      rating: 4.7,
      peopleBought: 5000,
      price: "₹799",
    },
    {
      image: "reactImage.jpeg",
      topic: "Node.js Backend Development",
      duration: "35 hours",
      lastUpdated: "Oct 2023",
      rating: 4.6,
      peopleBought: 4100,
      price: "₹899",
    },
    {
      image: "reactImage.jpeg",
      topic: "Python for Beginners",
      duration: "20 hours",
      lastUpdated: "Sep 2023",
      rating: 4.9,
      peopleBought: 7500,
      price: "₹499",
    },
    {
      image: "reactImage.jpeg",
      topic: "Data Science with Python",
      duration: "40 hours",
      lastUpdated: "Aug 2023",
      rating: 4.5,
      peopleBought: 8900,
      price: "₹999",
    },
    {
      image: "reactImage.jpeg",
      topic: "Machine Learning A-Z",
      duration: "45 hours",
      lastUpdated: "Jul 2023",
      rating: 4.7,
      peopleBought: 9500,
      price: "₹1099",
    },
    {
      image: "reactImage.jpeg",
      topic: "Full Stack Web Development",
      duration: "50 hours",
      lastUpdated: "Jun 2023",
      rating: 4.6,
      peopleBought: 12000,
      price: "₹1299",
    },
    {
      image: "reactImage.jpeg",
      topic: "Cloud Computing Basics",
      duration: "15 hours",
      lastUpdated: "May 2023",
      rating: 4.8,
      peopleBought: 4200,
      price: "₹549",
    },
    {
      image: "reactImage.jpeg",
      topic: "Cybersecurity Essentials",
      duration: "20 hours",
      lastUpdated: "Apr 2023",
      rating: 4.9,
      peopleBought: 3300,
      price: "₹899",
    },
    {
      image: "reactImage.jpeg",
      topic: "SQL & Database Management",
      duration: "18 hours",
      lastUpdated: "Mar 2023",
      rating: 4.7,
      peopleBought: 2900,
      price: "₹599",
    },
    {
      image: "reactImage.jpeg",
      topic: "UX/UI Design Fundamentals",
      duration: "10 hours",
      lastUpdated: "Feb 2023",
      rating: 4.6,
      peopleBought: 4700,
      price: "₹699",
    },
    {
      image: "reactImage.jpeg",
      topic: "Blockchain & Cryptocurrency",
      duration: "22 hours",
      lastUpdated: "Jan 2023",
      rating: 4.8,
      peopleBought: 5300,
      price: "₹899",
    },
    {
      image: "reactImage.jpeg",
      topic: "DevOps for Beginners",
      duration: "30 hours",
      lastUpdated: "Dec 2022",
      rating: 4.5,
      peopleBought: 3700,
      price: "₹749",
    },
    {
      image: "reactImage.jpeg",
      topic: "Artificial Intelligence Basics",
      duration: "25 hours",
      lastUpdated: "Nov 2022",
      rating: 4.7,
      peopleBought: 6100,
      price: "₹999",
    },
    {
      image: "reactImage.jpeg",
      topic: "Mobile App Development",
      duration: "28 hours",
      lastUpdated: "Oct 2022",
      rating: 4.6,
      peopleBought: 4600,
      price: "₹849",
    },
  ];
  
  export default BoughtCourses;
  